name: Contruindo e testando

on:   
    push:
          branches:
              - main

jobs: 
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: primeiro-passo 
              run: echo "Oi Mundo do DevOps" | echo "Irei listar os arquivos em tela "
            - name: Segundo passo
              run: ls -al
            - name: test_pipe
              run: |
                 echo "Hello, world" |  tee hello.txt | cat -n
